"""init schema

Revision ID: 4180eb68edad
Revises: 
Create Date: 2026-06-18 12:17:04.526621
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4180eb68edad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_audit_actor_time', 'audit_log', ['actor_user_id', 'created_at'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_metric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cohorts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_size_band', sa.String(), nullable=False),
    sa.Column('income_band', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('avg_tco2e', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('top_tco2e', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_size_band', 'income_band', 'region', name='uq_cohort')
    )
    op.create_table('emission_factors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('transport', 'energy', 'food', 'spend', 'home', name='category'), nullable=False),
    sa.Column('activity_key', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('gwp_method', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ef_lookup', 'emission_factors', ['category', 'activity_key', 'region', 'valid_from'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('income_band', sa.String(length=32), nullable=True),
    sa.Column('target_tco2e', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('category_rollups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('transport', 'energy', 'food', 'spend', 'home', name='category'), nullable=False),
    sa.Column('granularity', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.Date(), nullable=False),
    sa.Column('co2e_kg', sa.Float(), nullable=False),
    sa.Column('method_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category', 'granularity', 'bucket_start')
    )
    op.create_table('challenge_participants',
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id', 'user_id')
    )
    op.create_table('connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('bank', 'telematics', 'meter', name='providerkind'), nullable=False),
    sa.Column('status', sa.Enum('disconnected', 'connecting', 'connected', 'needs_attention', name='connstatus'), nullable=False),
    sa.Column('external_account_ref', sa.String(), nullable=True),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'external_account_ref', name='uq_conn_account')
    )
    op.create_index(op.f('ix_connections_user_id'), 'connections', ['user_id'], unique=False)
    op.create_table('dsr_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('export', 'erase', name='dsrkind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsr_jobs_user_id'), 'dsr_jobs', ['user_id'], unique=False)
    op.create_table('footprint_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('total_tco2e', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('delta_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('seed', 'regressing', 'plateau', 'improving', 'thriving', name='biomestatus'), nullable=False),
    sa.Column('health', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('target_tco2e', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'range', name='uq_snapshot_range')
    )
    op.create_index(op.f('ix_footprint_snapshots_user_id'), 'footprint_snapshots', ['user_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('response_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('transport', 'energy', 'food', 'spend', 'home', name='category'), nullable=False),
    sa.Column('source_type', sa.Enum('transaction', 'trip', 'energy', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('activity', 'spend', 'estimated', name='calcmethod'), nullable=False),
    sa.Column('co2e_kg', sa.Float(), nullable=False),
    sa.Column('factor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factor_id'], ['emission_factors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'occurred_at'),
    postgresql_partition_by='RANGE (occurred_at)'
    )
    op.create_index('ix_ledger_user_cat', 'ledger_entries', ['user_id', 'category', 'occurred_at'], unique=False)
    op.create_index('ix_ledger_user_time', 'ledger_entries', ['user_id', 'occurred_at'], unique=False)
    op.create_table('privacy_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('location_precision', sa.Enum('precise', 'coarse_1km', 'event_only', name='locprecision'), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('action', 'default_swap', 'clean_window', name='nudgekind'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('carbon_saved_tco2e', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('money_saved_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('effort', sa.Enum('one_tap', 'five_min', 'setup', name='nudgeeffort'), nullable=False),
    sa.Column('window_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'acted', 'dismissed', 'expired', name='nudgestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rec_active', 'recommendations', ['user_id', 'score'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_cohort',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_manager_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('raw_energy_reads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('kwh', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('fuel', sa.String(), nullable=False),
    sa.Column('meter_ref', sa.String(), nullable=True),
    sa.Column('grid_intensity', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'interval_start'),
    sa.UniqueConstraint('user_id', 'external_id', 'interval_start', name='ux_energy_ext'),
    postgresql_partition_by='RANGE (interval_start)'
    )
    op.create_table('raw_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('mcc', sa.CHAR(length=4), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('spend_region', sa.String(), nullable=True),
    sa.Column('commodity_class', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'booked_at'),
    sa.UniqueConstraint('user_id', 'external_id', 'booked_at', name='ux_txn_ext'),
    postgresql_partition_by='RANGE (booked_at)'
    )
    op.create_table('raw_trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.Enum('car', 'bus', 'train', 'cycle', 'walk', 'flight', 'other', name='tripmode'), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'started_at'),
    sa.UniqueConstraint('user_id', 'external_id', 'started_at', name='ux_trip_ext'),
    postgresql_partition_by='RANGE (started_at)'
    )
    op.create_table('recommendation_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('realized_saving_tco2e', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_actions')
    op.drop_table('raw_trips')
    op.drop_table('raw_transactions')
    op.drop_table('raw_energy_reads')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('user_cohort')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index('ix_rec_active', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('privacy_settings')
    op.drop_index('ix_ledger_user_time', table_name='ledger_entries')
    op.drop_index('ix_ledger_user_cat', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_footprint_snapshots_user_id'), table_name='footprint_snapshots')
    op.drop_table('footprint_snapshots')
    op.drop_index(op.f('ix_dsr_jobs_user_id'), table_name='dsr_jobs')
    op.drop_table('dsr_jobs')
    op.drop_index(op.f('ix_connections_user_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('challenge_participants')
    op.drop_table('category_rollups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_ef_lookup', table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_table('cohorts')
    op.drop_table('challenges')
    op.drop_index('ix_audit_actor_time', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
