"""onboarding_profiles

Revision ID: a25fb626e0c4
Revises: 4180eb68edad
Create Date: 2026-06-18 13:01:48.202334
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a25fb626e0c4'
down_revision: Union[str, None] = '4180eb68edad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('home_type', sa.Enum('flat', 'terraced', 'semi', 'detached', name='hometype'), nullable=False),
    sa.Column('energy_source', sa.Enum('standard', 'green', 'renewable', name='energysource'), nullable=False),
    sa.Column('diet', sa.Enum('meat_heavy', 'average', 'low_meat', 'vegetarian', 'vegan', name='diet'), nullable=False),
    sa.Column('car_type', sa.Enum('none', 'petrol', 'diesel', 'hybrid', 'ev', name='cartype'), nullable=False),
    sa.Column('car_km_per_week', sa.Integer(), nullable=False),
    sa.Column('short_flights_per_year', sa.Integer(), nullable=False),
    sa.Column('long_flights_per_year', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_profiles')
    # ### end Alembic commands ###
