"""onboarding status and step

Revision ID: d339de8f9e19
Revises: c3f1a2b4d5e6
Create Date: 2026-06-19 08:44:07.317761
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd339de8f9e19'
down_revision: Union[str, None] = 'c3f1a2b4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: the autogenerated drops of the *_default PARTITIONs were removed —
    # those partitions are managed by the c3f1a2b4d5e6 migration, not the models,
    # so Alembic wrongly flags them as "removed tables".
    onboarding_status = sa.Enum('in_progress', 'completed', name='onboardingstatus')
    onboarding_status.create(op.get_bind(), checkfirst=True)
    op.add_column('onboarding_profiles', sa.Column('status', onboarding_status, server_default='in_progress', nullable=False))
    op.add_column('onboarding_profiles', sa.Column('current_step', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # backfill: rows that already finished are completed (the column default only
    # covers genuinely in-progress rows)
    op.execute(
        "UPDATE onboarding_profiles SET status = 'completed', current_step = 8 "
        "WHERE completed_at IS NOT NULL"
    )


def downgrade() -> None:
    op.drop_column('onboarding_profiles', 'current_step')
    op.drop_column('onboarding_profiles', 'status')
    sa.Enum(name='onboardingstatus').drop(op.get_bind(), checkfirst=True)
    return
    op.create_table('raw_transactions_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount_minor', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.CHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('mcc', sa.CHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('merchant', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('spend_region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('commodity_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name='raw_transactions_connection_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='raw_transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'booked_at', name='raw_transactions_default_pkey'),
    sa.UniqueConstraint('user_id', 'external_id', 'booked_at', name='raw_transactions_default_user_id_external_id_booked_at_key')
    )
    op.create_table('raw_trips_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('mode', postgresql.ENUM('car', 'bus', 'train', 'cycle', 'walk', 'flight', 'other', name='tripmode'), autoincrement=False, nullable=False),
    sa.Column('distance_m', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name='raw_trips_connection_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='raw_trips_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'started_at', name='raw_trips_default_pkey'),
    sa.UniqueConstraint('user_id', 'external_id', 'started_at', name='raw_trips_default_user_id_external_id_started_at_key')
    )
    op.create_table('ledger_entries_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('transport', 'energy', 'food', 'spend', 'home', name='category'), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('transaction', 'trip', 'energy', name='sourcetype'), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('method', postgresql.ENUM('activity', 'spend', 'estimated', name='calcmethod'), autoincrement=False, nullable=False),
    sa.Column('co2e_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('factor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factor_id'], ['emission_factors.id'], name='ledger_entries_factor_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ledger_entries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name='ledger_entries_default_pkey')
    )
    op.create_index('ledger_entries_default_user_id_occurred_at_idx', 'ledger_entries_default', ['user_id', 'occurred_at'], unique=False)
    op.create_index('ledger_entries_default_user_id_category_occurred_at_idx', 'ledger_entries_default', ['user_id', 'category', 'occurred_at'], unique=False)
    op.create_table('raw_energy_reads_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interval_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kwh', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False),
    sa.Column('fuel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meter_ref', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grid_intensity', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name='raw_energy_reads_connection_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='raw_energy_reads_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'interval_start', name='raw_energy_reads_default_pkey'),
    sa.UniqueConstraint('user_id', 'external_id', 'interval_start', name='raw_energy_reads_default_user_id_external_id_interval_start_key')
    )
    op.create_table('audit_log_default',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_at', name='audit_log_default_pkey')
    )
    op.create_index('audit_log_default_actor_user_id_created_at_idx', 'audit_log_default', ['actor_user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
